INSERT INTO category (description) VALUES ('Vegan');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Dessert');
INSERT INTO category (description) VALUES ('Pasta');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');
INSERT INTO unit_of_measure (description) VALUES ('Ounce');